version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fuelphp-app
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html/my_fuel_project
      # ★以下の行を追加（作ったphp.iniを、コンテナ内の設定フォルダにマウント）
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - fuelphp-network

  db:
    build:
      context: ../
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intern_kadai_db
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - fuelphp-network

networks:
  fuelphp-network:
    driver: bridge
